// Pokemon-style game DATA: types, moves, monsters, sprites, map, NPCs
window.PMD = (() => {
'use strict';

// ===== Types & effectiveness =====
const TYPES = ['normal','fire','water','grass','electric','ice','rock','ghost','flying','poison','dragon'];
const TYPE_EFFECT = {
  normal:   { rock:0.5, ghost:0 },
  fire:     { fire:0.5, water:0.5, grass:2, ice:2, rock:0.5, dragon:0.5 },
  water:    { fire:2, water:0.5, grass:0.5, rock:2, dragon:0.5 },
  grass:    { fire:0.5, water:2, grass:0.5, rock:2, flying:0.5, poison:0.5, dragon:0.5 },
  electric: { water:2, grass:0.5, electric:0.5, flying:2, dragon:0.5 },
  ice:      { fire:0.5, water:0.5, grass:2, ice:0.5, flying:2, dragon:2 },
  rock:     { fire:2, ice:2, flying:2 },
  ghost:    { ghost:2, normal:0 },
  flying:   { electric:0.5, grass:2, ice:0.5, rock:0.5 },
  poison:   { grass:2, poison:0.5, rock:0.5, ghost:0.5 },
  dragon:   { dragon:2, ice:0.5 },
};
function eff(att, def) { return (TYPE_EFFECT[att] && TYPE_EFFECT[att][def] !== undefined) ? TYPE_EFFECT[att][def] : 1; }

// ===== Moves =====
const MOVES = {
  tackle:       { name:'たいあたり',     type:'normal',   power:40, acc:100 },
  scratch:      { name:'ひっかく',       type:'normal',   power:40, acc:100 },
  slash:        { name:'きりさく',       type:'normal',   power:70, acc:100 },
  ember:        { name:'ひのこ',         type:'fire',     power:40, acc:100 },
  flameKick:    { name:'ほのおキック',   type:'fire',     power:75, acc:95 },
  fireBlast:    { name:'だいもんじ',     type:'fire',     power:110,acc:85 },
  waterGun:     { name:'みずでっぽう',   type:'water',    power:40, acc:100 },
  hydroPump:    { name:'ハイドロポンプ', type:'water',    power:110,acc:80 },
  vineWhip:     { name:'つるのムチ',     type:'grass',    power:45, acc:100 },
  leafBlade:    { name:'リーフブレード', type:'grass',    power:90, acc:100 },
  thunderShock: { name:'でんきショック', type:'electric', power:40, acc:100 },
  thunderBolt:  { name:'かみなり',       type:'electric', power:90, acc:100 },
  iceShard:     { name:'こおりのつぶて', type:'ice',      power:45, acc:100 },
  rockThrow:    { name:'いわおとし',     type:'rock',     power:50, acc:90 },
  rockSlide:    { name:'いわなだれ',     type:'rock',     power:75, acc:90 },
  lick:         { name:'したでなめる',   type:'ghost',    power:30, acc:100 },
  shadowBall:   { name:'シャドーボール', type:'ghost',    power:80, acc:100 },
  gust:         { name:'かぜおこし',     type:'flying',   power:40, acc:100 },
  poisonSting:  { name:'どくばり',       type:'poison',   power:35, acc:100 },
  sludge:       { name:'ヘドロこうげき', type:'poison',   power:65, acc:100 },
  dragonRage:   { name:'りゅうのいかり', type:'dragon',   power:60, acc:100 },
  dragonClaw:   { name:'ドラゴンクロー', type:'dragon',   power:80, acc:100 },
};

// ===== Monsters =====
const MONSTERS = {
  leafin:   { name:'リーファ',     type:'grass',    hp:45, atk:49, def:49, spd:45, catch:45,  exp:65,  moves:['tackle','vineWhip','leafBlade','slash'], legend:false, desc:'はっぱ頭のおとなしいモンスター。' },
  embaru:   { name:'エンバル',     type:'fire',     hp:39, atk:52, def:43, spd:65, catch:45,  exp:65,  moves:['scratch','ember','flameKick','slash'], legend:false, desc:'尻尾の炎が元気の証。' },
  akwami:   { name:'アクワミ',     type:'water',    hp:44, atk:48, def:65, spd:43, catch:45,  exp:65,  moves:['tackle','waterGun','hydroPump','slash'], legend:false, desc:'青い甲羅のカメ。' },
  pikamon:  { name:'ピカモン',     type:'electric', hp:35, atk:55, def:40, spd:90, catch:80,  exp:53,  moves:['tackle','thunderShock','thunderBolt','slash'], legend:false, desc:'ほっぺに電気をためる。' },
  rockfun:  { name:'ロックフン',   type:'rock',     hp:40, atk:80, def:100,spd:20, catch:100, exp:53,  moves:['tackle','rockThrow','rockSlide','scratch'], legend:false, desc:'岩のかたまり。重い。' },
  pijiko:   { name:'ピジコ',       type:'flying',   hp:40, atk:45, def:40, spd:56, catch:200, exp:53,  moves:['tackle','gust','slash','scratch'], legend:false, desc:'どこにでもいる小鳥。' },
  kodoku:   { name:'コドク',       type:'poison',   hp:40, atk:65, def:50, spd:35, catch:190, exp:56,  moves:['tackle','poisonSting','sludge','lick'], legend:false, desc:'ガス状の毒モンスター。' },
  nyanmel:  { name:'ニャンメル',   type:'normal',   hp:40, atk:45, def:35, spd:90, catch:255, exp:60,  moves:['scratch','slash','tackle','lick'], legend:false, desc:'いたずら好きなネコ。' },
  icepen:   { name:'アイスペン',   type:'ice',      hp:50, atk:50, def:50, spd:55, catch:90,  exp:65,  moves:['tackle','iceShard','waterGun','gust'], legend:false, desc:'こおりの上を滑るペンギン。' },
  obakero:  { name:'オバケロ',     type:'ghost',    hp:30, atk:35, def:30, spd:80, catch:190, exp:95,  moves:['tackle','lick','shadowBall','sludge'], legend:false, desc:'夜にあらわれるゆうれい。' },
  draginus: { name:'ドラギナス',   type:'dragon',   hp:91, atk:134,def:95, spd:80, catch:3,   exp:270, moves:['dragonClaw','dragonRage','slash','flameKick'], legend:true, desc:'伝説のドラゴン。湖の主。' },
  honooou:  { name:'ホノオウ',     type:'fire',     hp:106,atk:130,def:90, spd:90, catch:3,   exp:261, moves:['ember','flameKick','fireBlast','gust'], legend:true, desc:'火山に住む不死鳥。' },
};

// ===== Compact pixel sprite renderer =====
// Each sprite is 16 lines x 16 chars. Palette per character.
const PAL = {
  '.': null,
  o: '#1a1a2e',
  W: '#ffffff',
  R: '#ef5350', r: '#c62828',
  O: '#ffa726',
  Y: '#ffd54f', y: '#f9a825',
  G: '#66bb6a', g: '#2e7d32',
  B: '#42a5f5', b: '#1565c0',
  P: '#ce93d8', p: '#7e57c2',
  K: '#80deea', k: '#0097a7',
  C: '#fff9c4',
  N: '#8d6e63', n: '#5d4037',
  H: '#bdbdbd', h: '#757575',
  S: '#f48fb1', s: '#ad1457',
  Q: '#ce93d8', q: '#4a148c',
  V: '#80cbc4',
};
function drawSprite(ctx, sprite, x, y, scale) {
  const lines = sprite.split('\n').filter(l => l.length > 0);
  for (let r = 0; r < lines.length; r++) {
    for (let c = 0; c < lines[r].length; c++) {
      const ch = lines[r][c];
      const col = PAL[ch];
      if (col) {
        ctx.fillStyle = col;
        ctx.fillRect(x + c * scale, y + r * scale, scale, scale);
      }
    }
  }
}

// ===== Monster sprites (16x16) =====
const SPRITES = {
  leafin: `
.......gg.......
......gGGg......
.....gGggGg.....
......gGg.......
.......g........
.....ooooo......
....oGGGGGo.....
...oGGCCCGGo....
..oGCWoCWoCGo...
..oGCCCCCCCGo...
..oGCoooooCGo...
..oGCWWWWWCGo...
...oGGGGGGGo....
....oogggoo.....
.....o.o.o......
................`,
  embaru: `
.......OY.......
......OYO.......
......YOY.......
.....ooooo......
....oOOOOOo.....
...oOOWoWOOo....
..oOORRRRROOo...
..oOOOOOOOOOo...
..oOOWWoWWOOo...
...oOOOOOOOo....
....oOOrrOOo....
.....oOrro......
.....OOoOO......
....rOoooOr.....
....OO...OO.....
................`,
  akwami: `
................
......BBB.......
.....BbbbB......
....BbbBbbB.....
....BoBBBoB.....
.....BBBBB......
...nnNNNNNnn....
..nNHHHHHHHnN...
..nNHCCCCCHNn...
..nNHCBoBoCHNn..
..nNHCBBBBBCHN..
..nNHCBoBoBCHN..
..nNHHHHHHHNn...
..nnNNNNNnnn....
....nnnnnn......
................`,
  pikamon: `
.....o....o.....
.....oo..oo.....
....oYYooYYo....
...oYYYYYYYYo...
..oYYYWoYWYYYo..
..oYYsYYsYYYo...
..oYYYYYYYYYo...
..oYYWWWWWYYo...
..oYYYYYYYYYo...
...oYYYyyYYYo...
....oYYyyYYo....
.....oyyyyo.....
....yYYy.yYYy...
...yYYY...YYYy..
..yYY.....YYYy..
................`,
  rockfun: `
................
....HHHHHHH.....
...HhhHHhhhH....
..HhHHHHHHhhH...
..HHWoHHHWoHH...
..HHHHHHHHHHH...
..HhHHooooHhh...
..HHhhHHHHhhH...
..HHhHHHHHhhH...
...HhhHHHhhh....
....HHHHHHH.....
...hh.....hh....
..HhH.....HhH...
..hh.......hh...
................
................`,
  pijiko: `
................
......NNN.......
.....NnnnN......
....NnNNNnN.....
....NWoWoWN.....
....NyYyYyN.....
...NNnnnnnNN....
..NnNnNNNnnNN...
..nNnnnnnnnNn...
...NNNnnnNNN....
....NNNnnNNN....
.....NN.NN......
.....NN.NN......
.....yY.Yy......
................
................`,
  kodoku: `
................
.....pppp.......
....pPPPPp......
...pPPPPPPp.....
..pPPpPPpPPp....
..pPWoPPoWPp....
..pPPPPPPPPp....
..pPPoooooPp....
..pPPPPPPPPp....
...pPPPPPPp.....
....pppppp......
....pp..pp......
....p.pp.p......
.....p..p.......
................
................`,
  nyanmel: `
....YY....YY....
....YOY..YOY....
....YYYooYYY....
...YYYCYYCYYY...
..YYCWoCCoWCYY..
..YYCYYsYYYCYY..
..YYCYYYYYYCYY..
..YYCWWWWWWCYY..
..YYYYYYYYYYY...
...YYYYYYYYY....
....YY.YY.YY....
....YY.YY.YY....
.....Y.Y.Y......
................
................
................`,
  icepen: `
................
.....BBBBB......
....BbbbbbB.....
....BWoBoWB.....
....BBBOBBB.....
...BBCCCCCBB....
..BBCCCCCCCBB...
..BCCWCCCWCCB...
..BCCCCCCCCCB...
..BBCCCCCCCBB...
...BBBBBBBBB....
....BB...BB.....
.....OO.OO......
.....OOOOO......
................
................`,
  obakero: `
................
......qqq.......
....qqqQqqq.....
...qQQQQQQQq....
..qQQQQQQQQQq...
..qQWoQQQoWQq...
..qQQQQQQQQQq...
..qQQqooooqQq...
..qQQQqooqQQq...
..qQQQQQQQQQq...
..qQpppQpppQq...
..qpQQpQpQQpq...
...pq.pq.pq.....
....q.q.q.q.....
................
................`,
  draginus: `
......pPp.......
.....pPPPp......
....pPWoWPp.....
...PPPPPPPPP....
..pPCCCCCCCPp...
..pPCpPPPpCPp...
.pPPPPPPPPPPPp..
pPPCWoPPPoWCPPp.
pPPCCPPPPPCCPPp.
.pPPPCCCCCPPPp..
..pPPCCoCCPPp...
...pPPCCCPPp....
....pppppp......
...pP.....Pp....
..pPP.....PPp...
.................`,
  honooou: `
.......RY.......
......ROYO......
.....ORYYRO.....
....ROYYYYOR....
...ORYYYYYYO....
..ORYYWoWoYRO...
..ORYYYYYYYRO...
.ORYYYRROOOYYRO.
ORYYYRROOOORYYRO
.ORYYRRRROOYYRO.
..ORYYYYYYYRO...
...OYYRRRRYO....
....RYYYYYR.....
....ROOOOOR.....
.....rorororor..
................`,
};

// ===== Player & NPC sprites (16x16) =====
const PLAYER_SPR = {
  down: `
......hHHh......
.....hHHHHh.....
.....hHWWHh.....
.....hHooHh.....
......hooh......
....hhCCCChh....
....hCYRYCh.....
....hCYRYCh.....
....hCCCCCh.....
....hCYRYCh.....
....hhhhhhh.....
.....HH..HH.....
.....HH..HH.....
.....nN..Nn.....
................
................`,
  up: `
......hHHh......
.....hHHHHh.....
.....hHHHHh.....
.....hHHHHh.....
......hHHh......
....hhCCCChh....
....hCYRYCh.....
....hCYRYCh.....
....hCCCCCh.....
....hCYRYCh.....
....hhhhhhh.....
.....HH..HH.....
.....HH..HH.....
.....nN..Nn.....
................
................`,
  left: `
......hHHh......
.....hHHHHh.....
.....hHWHHh.....
.....hHooHh.....
......hooh......
.....hCCCh......
....hCYRYCh.....
....hCYRYCh.....
....hCCCCCh.....
....hCYRYCh.....
....hhhhhhh.....
.....HH..HH.....
.....HH..HH.....
.....nN..Nn.....
................
................`,
  right: `
......hHHh......
.....hHHHHh.....
.....hHHWHh.....
.....hHooHh.....
......hooh......
......hCCCh.....
....hCYRYCh.....
....hCYRYCh.....
....hCCCCCh.....
....hCYRYCh.....
....hhhhhhh.....
.....HH..HH.....
.....HH..HH.....
.....nN..Nn.....
................
................`,
};

const NPC_SPR = {
  oldman: `
......WWWW......
.....WWWWWW.....
.....WCCCCW.....
.....hCooCh.....
......hooh......
....hhBBBBhh....
....hBBBBBh.....
....hBBgBBh.....
....hBBBBBh.....
....hBBBBBh.....
....hhhhhhh.....
.....NN..NN.....
.....nn..nn.....
................
................
................`,
  gym: `
......yyyy......
.....yYYYYy.....
.....yYRRYy.....
.....hCooCh.....
......hooh......
....hhYYYYhh....
....hYrYrYh.....
....hYYYYYh.....
....hYRRRYh.....
....hYYYYYh.....
....hhhhhhh.....
.....HH..HH.....
.....hh..hh.....
................
................
................`,
};

// ===== Tile rendering =====
const TILES = {
  '.': { walk: true,  paint: (c,x,y,s) => {
    c.fillStyle = '#5fbb6a'; c.fillRect(x,y,s,s);
    c.fillStyle = '#4ca35a';
    for (let i = 0; i < 4; i++) {
      const px = x + ((i*7+3) % (s-2)), py = y + ((i*11+5) % (s-2));
      c.fillRect(px, py, 1, 1);
    }
  }},
  '~': { walk: true,  paint: (c,x,y,s) => {
    c.fillStyle = '#cdac6a'; c.fillRect(x,y,s,s);
    c.fillStyle = '#a88a4d';
    c.fillRect(x+2,y+3,2,1); c.fillRect(x+8,y+10,2,1); c.fillRect(x+5,y+7,1,2);
  }},
  't': { walk: true, encounter: true, paint: (c,x,y,s) => {
    c.fillStyle = '#3d8b46'; c.fillRect(x,y,s,s);
    c.fillStyle = '#2e6d36';
    c.fillRect(x+1,y+s-3,2,3); c.fillRect(x+5,y+s-4,2,4); c.fillRect(x+9,y+s-3,2,3); c.fillRect(x+13,y+s-4,2,4);
    c.fillStyle = '#5fbb6a';
    c.fillRect(x+2,y+s-2,1,1); c.fillRect(x+10,y+s-2,1,1);
  }},
  '#': { walk: false, paint: (c,x,y,s) => {
    c.fillStyle = '#6d6068'; c.fillRect(x,y,s,s);
    c.fillStyle = '#857783'; c.fillRect(x+1,y+1,s-2,s-2);
    c.fillStyle = '#4d4348'; c.fillRect(x,y+s-2,s,2); c.fillRect(x+s-2,y,2,s);
  }},
  'T': { walk: false, paint: (c,x,y,s) => {
    c.fillStyle = '#5fbb6a'; c.fillRect(x,y,s,s);
    c.fillStyle = '#2e6d36';
    c.beginPath(); c.arc(x+s/2, y+s/2-1, s/2-1, 0, Math.PI*2); c.fill();
    c.fillStyle = '#1f4d24';
    c.beginPath(); c.arc(x+s/2-3, y+s/2+1, 3, 0, Math.PI*2); c.fill();
    c.fillStyle = '#5d4037';
    c.fillRect(x+s/2-1, y+s-4, 2, 4);
  }},
  'W': { walk: false, paint: (c,x,y,s) => {
    c.fillStyle = '#3a87ff'; c.fillRect(x,y,s,s);
    c.fillStyle = '#82b8ff';
    c.fillRect(x+2,y+3,3,1); c.fillRect(x+8,y+9,3,1); c.fillRect(x+11,y+5,2,1);
  }},
  'B': { walk: false, paint: (c,x,y,s) => {
    c.fillStyle = '#b67651'; c.fillRect(x,y,s,s);
    c.strokeStyle = '#7d4f33'; c.lineWidth = 1;
    for (let i = 0; i < s; i += 4) c.strokeRect(x+0.5,y+i+0.5,s-1,4);
  }},
  'D': { walk: true, door: true, paint: (c,x,y,s) => {
    c.fillStyle = '#5d4037'; c.fillRect(x,y,s,s);
    c.fillStyle = '#3e2723'; c.fillRect(x+2,y+2,s-4,s-2);
    c.fillStyle = '#ffd54f'; c.fillRect(x+s-5,y+s/2,2,2);
  }},
  'R': { walk: true, paint: (c,x,y,s) => { // roof
    c.fillStyle = '#c62828'; c.fillRect(x,y,s,s);
    c.fillStyle = '#8e0000'; c.fillRect(x,y,s,2);
    c.fillStyle = '#ef5350'; c.fillRect(x,y+s-2,s,2);
  }},
  'F': { walk: true, paint: (c,x,y,s) => {
    TILES['.'].paint(c,x,y,s);
    c.fillStyle = '#f48fb1'; c.fillRect(x+s/2-1,y+s/2-1,2,2);
    c.fillStyle = '#ffeb3b'; c.fillRect(x+s/2,y+s/2,1,1);
  }},
  '-': { walk: 'bridge', paint: (c,x,y,s) => {
    c.fillStyle = '#3a87ff'; c.fillRect(x,y,s,s);
    c.fillStyle = '#a1887f'; c.fillRect(x,y+s/2-3,s,6);
    c.fillStyle = '#5d4037';
    for (let i = 0; i < s; i += 3) c.fillRect(x+i,y+s/2-3,1,6);
  }},
  '=': { walk: 'bridge', paint: (c,x,y,s) => TILES['-'].paint(c,x,y,s) }, // alias
  // Special interactive tiles - look like grass but trigger
  'S': { walk: false, npc: 'starter', paint: (c,x,y,s) => { TILES['.'].paint(c,x,y,s); drawSprite(c, NPC_SPR.oldman, x, y, s/16); }},
  'L': { walk: false, npc: 'gym', paint: (c,x,y,s) => { TILES['.'].paint(c,x,y,s); drawSprite(c, NPC_SPR.gym, x, y, s/16); }},
  '1': { walk: true, legend: 'draginus', paint: (c,x,y,s) => {
    TILES['.'].paint(c,x,y,s);
    c.fillStyle = 'rgba(126,87,194,0.35)'; c.fillRect(x,y,s,s);
    drawSprite(c, SPRITES.draginus, x, y, s/16);
  }},
  '2': { walk: true, legend: 'honooou', paint: (c,x,y,s) => {
    TILES['.'].paint(c,x,y,s);
    c.fillStyle = 'rgba(244,67,54,0.35)'; c.fillRect(x,y,s,s);
    drawSprite(c, SPRITES.honooou, x, y, s/16);
  }},
};

// ===== World map (40 wide x 22 tall) =====
const MAP_RAW = `
########################################
#TT.....BBBBB.......BBBBB......TTT.....#
#T......B.D.B.......B.D.B.......T......#
#.......BBRBB.......BBRBB......TT......#
#..S.........~~~~~........L....TT......#
#.~~~~~~~~~~~~..~~~~~~~~~~~~....T......#
#.~......T...~..~..F..F..~......T......#
#.~..tttttt..~..~........~......T......#
#.~..tttttt..~..~~..F..~~........T....#
#.~..tttttt..~...~~~~~~~..............#
#.~..........~........................#
#.~~~~~~~~~~~~~~..............tttt..F.#
#TT.................F........tttt....#
#TT........T...........T....tttt......#
#~~~~~~~~~--WWWWWWWWWW---~~~~~~~~~~....#
#.........-.WWWWWWWWWW.-.....~........#
#TTT......-.WWWWWWWWWW.-.....~........#
#T....######.WWWWWW...######.~..TTT...#
#.....#....##.WWWW..##....#..~..TT....#
#.....#..#..#######.######...~..T.....#
#.....#######...........T....~........#
########################################`;
const MAP_LINES = MAP_RAW.split('\n').filter(l => l.length > 0);
const MAP_W = MAP_LINES[0].length;
const MAP_H = MAP_LINES.length;
function tileAt(tx, ty) {
  if (tx < 0 || ty < 0 || tx >= MAP_W || ty >= MAP_H) return '#';
  const row = MAP_LINES[ty];
  return (row && row[tx]) || '#';
}

// ===== Encounter tables (by area) =====
function encounterAt(tx, ty) {
  // Determine area by position
  // Top half: route 1 - normal mons
  // Right side: forest - leafy mons
  // Bottom: cave/swamp - rare mons
  if (ty < 11) {
    return [
      { id: 'pijiko', lvl: [3, 6], w: 30 },
      { id: 'nyanmel', lvl: [2, 5], w: 25 },
      { id: 'kodoku', lvl: [3, 6], w: 15 },
      { id: 'pikamon', lvl: [4, 7], w: 10 },
      { id: 'leafin', lvl: [4, 7], w: 8 },
      { id: 'embaru', lvl: [5, 8], w: 6 },
      { id: 'akwami', lvl: [5, 8], w: 6 },
    ];
  } else {
    return [
      { id: 'rockfun', lvl: [6, 12], w: 25 },
      { id: 'obakero', lvl: [7, 12], w: 20 },
      { id: 'icepen', lvl: [8, 13], w: 18 },
      { id: 'kodoku', lvl: [6, 10], w: 15 },
      { id: 'pijiko', lvl: [5, 10], w: 12 },
      { id: 'pikamon', lvl: [8, 12], w: 10 },
    ];
  }
}
function pickEncounter(table) {
  const total = table.reduce((s, e) => s + e.w, 0);
  let r = Math.random() * total;
  for (const e of table) { r -= e.w; if (r <= 0) {
    const lvl = e.lvl[0] + Math.floor(Math.random() * (e.lvl[1] - e.lvl[0] + 1));
    return { id: e.id, level: lvl };
  } }
  return { id: table[0].id, level: table[0].lvl[0] };
}

// ===== Build a wild monster instance from species + level =====
function makeMon(id, level) {
  const sp = MONSTERS[id];
  const maxHp = Math.floor((2 * sp.hp * level) / 100) + level + 10;
  const atk = Math.floor((2 * sp.atk * level) / 100) + 5;
  const def = Math.floor((2 * sp.def * level) / 100) + 5;
  const spd = Math.floor((2 * sp.spd * level) / 100) + 5;
  return {
    id, name: sp.name, type: sp.type, level,
    maxHp, hp: maxHp, atk, def, spd,
    moves: sp.moves.slice(),
    catch: sp.catch, exp: sp.exp,
    legend: sp.legend, owned: false,
    xp: 0, xpNext: Math.floor(Math.pow(level + 1, 3)),
  };
}

return { TYPES, TYPE_EFFECT, eff, MOVES, MONSTERS, SPRITES, PLAYER_SPR, NPC_SPR, TILES,
  drawSprite, MAP_LINES, MAP_W, MAP_H, tileAt, encounterAt, pickEncounter, makeMon };
})();
